name: CI-CD-Pipline to AWS
env: 
  S3_BUCKET_NAME     : "ivan-test-github"
  EB_APPLICATION_NAME: "Ivan-env-github"
  EB_ENVIRONMENT_NAME: "Ivan-first-app777" 
  DEPLOY_PACKAGE_NAME: "ivan_app_$(( github.sha )).zip"
  AWS_REGION_NAME    : "us-east-2"
  
  
  
  
on:
  push:
    branches:
      - master

jobs:
  1-pipline:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
    - uses: actions/checkout@v2
      
    - name: Create in Zip depl package
    - uses: zip -r $(( env.DEPLOY_PACKAGE_NAME )) ./ -x *.git*
      
      
      
     
      
 
