name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "ivan-test-github"
  EB_APPLICATION_NAME       : "Ivan-env-github"
  EB_ENVIRONMENT_NAME       : "Ivan-env-github-env" 
  DEPLOY_PACKAGE_NAME       : "Newapp-for-jenkins_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"
  
on:
  push:
    branches:
      - master

jobs:
  binstock1:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
    
    - name: Create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id.   : ${{ secrets.AWS_secret_key }}
        aws-secret-access-key: ${{ secrets.AWS_secret2_key }}
        aws-region.          : ${{ env.AWS_REGION_NAME }}
    
    - name: copy deployment package to s3 bucket
   
      

      
      
      
     
      
 
