#----------------iIvan------------------
#----------------2020-------------------


name: my-1-file
env:
  APPLICATION_NAME    : "MyBestApp"
  DEPLOY_PACKAGE_NAME : "app-deploy-ver-${{ github.sha }}" 

on: 
  push:
    branches:
      - master 


jobs:
  my-testin-1:
    runs-on : ubuntu-latest
    steps   :
      - name: Print Hello Message in Testing
        run : echo "Hello iIvan testing"
      - name: Execure few commands
        run : |
          echo "Message1"
          echo "Message2"
          echo "Message3"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
      - name: List curent folder
        run : ls -la 
    
  my-deploy1:
    runs-on: ubuntu-latest
    needs: [my-testin-1]    
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello iIvan deploy job"
      - name: Print Deploy package
        run: echo "deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
